spring:
  application:
    name: vibecoder

  datasource:
    url: jdbc:postgresql://localhost:5432/vibecoder?TimeZone=UTC
    username: vibesql
    password: root2305
    driver-class-name: org.postgresql.Driver

  ai:
    azure:
      openai:
        api-key: ${DIAL_API_KEY}
        endpoint: ${DIAL_ENDPOINT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

cors:
  allowed-origins: "*"
  allow-credentials: false