app:
  jwt:
    secret: qCaXEibAKRNDlDZXQ8c0DMBi5FM6OTVK4z4ornZZkTM=
    expiration: 864000000 # 24 hours in milliseconds

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  application:
    name: vibecoder

  datasource:
    url: jdbc:postgresql://localhost:5432/vibecoder
    username: postgres
    password: 2305
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create   # use: none | validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  allowed-origins: "*"
  allow-credentials: false